apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: my-deployment
  name: my-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: my-deployment
  template: 
    metadata: 
      labels: 
        app: my-deployment
    spec: 
      containers: 
        - 
          image: "nginx:1.14.2"
          name: nginx
          ports: 
            - 
              containerPort: 80
